spring.application.name=smart-hire-ai-backend
spring.config.import=optional:file:.env[.properties]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
security.jwt.expiration-ms=86400000
security.jwt.secret=${SECURITY_JWT_SECRET}
ai.service.url=http://localhost:8000
